micronaut:
  application:
    name: totrackit-api
  server:
    port: 8080
  data:
    default:
      dialect: POSTGRES
    pageable:
      max-page-size: 1000

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/totrackit
    username: totrackit
    password: totrackit
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 10

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true
      baseline-version: 0

logger:
  levels:
    com.totrackit: DEBUG
    io.micronaut.data: DEBUG