micronaut:
  application:
    name: totrackit-api
  server:
    port: 8080
  data:
    default:
      dialect: POSTGRES
    pageable:
      max-page-size: 1000
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  openapi:
    path: /openapi
    server:
      description: ToTrackIt API Server
      url: http://localhost:8080
  task:
    scheduler:
      enabled: true

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/totrackit
    username: totrackit
    password: totrackit
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 10

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true
      baseline-version: 0

logger:
  levels:
    com.totrackit: DEBUG
    io.micronaut.data: DEBUG

endpoints:
  all:
    enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
  prometheus:
    enabled: true

micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true