# Alertmanager configuration for ToTrackIt
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@totrackit.local'
  smtp_auth_username: ''
  smtp_auth_password: ''

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/'
        send_resolved: true

  # Example email configuration (uncomment and configure as needed)
  # - name: 'email-alerts'
  #   email_configs:
  #     - to: 'admin@totrackit.local'
  #       subject: 'ToTrackIt Alert: {{ .GroupLabels.alertname }}'
  #       body: |
  #         {{ range .Alerts }}
  #         Alert: {{ .Annotations.summary }}
  #         Description: {{ .Annotations.description }}
  #         {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']