# ToTrackIt alerting rules
groups:
  - name: totrackit-app
    rules:
      - alert: ToTrackItAppDown
        expr: up{job="totrackit-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "ToTrackIt application is down"
          description: "ToTrackIt application has been down for more than 1 minute."

      - alert: ToTrackItHighResponseTime
        expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket{job="totrackit-app"}[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "ToTrackIt high response time"
          description: "95th percentile response time is {{ $value }}s for more than 5 minutes."

      - alert: ToTrackItHighErrorRate
        expr: rate(http_server_requests_total{job="totrackit-app",status=~"5.."}[5m]) / rate(http_server_requests_total{job="totrackit-app"}[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "ToTrackIt high error rate"
          description: "Error rate is {{ $value | humanizePercentage }} for more than 2 minutes."

  - name: totrackit-database
    rules:
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 1 minute."

      - alert: PostgreSQLHighConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL high connection usage"
          description: "PostgreSQL connection usage is {{ $value | humanizePercentage }}."

  - name: system-resources
    rules:
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 90% for more than 5 minutes."

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% for more than 10 minutes."